#
# DEFAULT FORM TYPES
#
parameters: ~

services:

  #
  # Widget Types
  #
  linestorm.blog.form.type.widget.dropzone:
        class: LineStorm\BlogBundle\Form\Type\DropZoneType
        tags:
            - { name: form.type, alias: dropzone }

  linestorm.blog.form.type.widget.tag:
        class: LineStorm\BlogBundle\Form\Type\TagType
        arguments: [@linestorm.blog.model_manager]
        tags:
            - { name: form.type, alias: tag }

  #
  # Form Types
  #
  linestorm.blog.form.type.post:
        class: LineStorm\BlogBundle\Form\PostFormType
        arguments: [@linestorm.blog.model_manager, @linestorm.blog.module_manager]
        tags:
            - { name: form.type, alias: linestorm_blog_form_post }

  linestorm.blog.form.type.post.article:
        class: LineStorm\BlogBundle\Form\PostArticleFormType
        arguments: [@linestorm.blog.model_manager]
        tags:
            - { name: form.type, alias: linestorm_blog_form_post_article }

  linestorm.blog.form.type.post.gallery:
        class: LineStorm\BlogBundle\Form\PostGalleryFormType
        arguments: [@linestorm.blog.model_manager]
        tags:
            - { name: form.type, alias: linestorm_blog_form_post_gallery }

  linestorm.blog.form.type.post.gallery.image:
        class: LineStorm\BlogBundle\Form\PostGalleryImageFormType
        arguments: [@linestorm.blog.model_manager]
        tags:
            - { name: form.type, alias: linestorm_blog_form_post_gallery_image }

  linestorm.blog.form.type.tag:
        class: LineStorm\BlogBundle\Form\TagFormType
        arguments: [@linestorm.blog.model_manager]
        tags:
            - { name: form.type, alias: linestorm_blog_form_tag }

  linestorm.blog.form.type.media:
        class: LineStorm\BlogBundle\Form\MediaFormType
        arguments: [@linestorm.blog.media_manager]
        tags:
            - { name: form.type, alias: linestorm_blog_form_media }


  linestorm.blog.form.type.category:
        class: LineStorm\BlogBundle\Form\CategoryFormType
        arguments: [@linestorm.blog.model_manager]
        tags:
            - { name: form.type, alias: linestorm_blog_form_category }

